# Generated by Django 2.2.1 on 2019-05-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('employee_name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gross Pay')),
            ],
            options={
                'ordering': ['employee_name'],
            },
        ),
    ]
